[server]
debug_trace = false

[vpc]
iam_client_id = "bx"
iam_client_secret = "bx"
gc_token_exchange_endpoint_url = "https://iam.bluemix.net"
gc_riaas_endpoint_url = "https://eu-de.iaas.cloud.ibm.com"
gc_resource_group_id = "xxx"
gc_api_key = "yyy"
provider_type = "gc"
