apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-block-pvc1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-block-5iops-tier
