apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-block-pvc-good
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-block-5iops-tier
